# Generated by Django 5.2 on 2025-04-05 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAPIKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_api_key', models.CharField(blank=True, help_text='Encrypted OpenAI API Key', max_length=255, null=True)),
                ('gemini_api_key', models.CharField(blank=True, help_text='Encrypted Google AI (Gemini) API Key', max_length=255, null=True)),
                ('claude_api_key', models.CharField(blank=True, help_text='Encrypted Anthropic (Claude) API Key', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User API Keys',
            },
        ),
    ]
